#// Developer: Aradhya Jain (G01462086)
#// Developer: Gayatri Ramchandra Vaidya (G01460522)
#// Developer: Sanath Kumar Parimi (G01442785)
#// Developer: Saksham Nayyar (G01462522)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
      - name: survey-container
        image: ajain30/survey-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
