apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
      - name: survey-container
        image: ajain30/survey-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
