#// Developer: Aradhya Jain (G01462086)
#// Developer: Gayatri Ramchandra Vaidya (G01460522)
#// Developer: Sanath Kumar Parimi (G01442785)
#// Developer: Saksham Nayyar (G01462522)


apiVersion: v1
kind: Service
metadata:
  name: survey-svc
spec:
  selector:
    app: survey
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30022
