apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.21.95"],"port":30022,"protocol":"TCP","serviceName":"default:survey-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["default/survey"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-11-21T01:33:35Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-11-21T01:33:35Z'
  name: survey-nodeport
  namespace: default
  resourceVersion: '8199'
  uid: cd9e29c5-87cd-479a-936e-9e2473d6cab6
spec:
  clusterIP: 10.43.149.81
  clusterIPs:
    - 10.43.149.81
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: survey-svc
      nodePort: 30022
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-survey
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
